// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wziowrdrypztdgfztovr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6aW93cmRyeXB6dGRnZnp0b3ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NDcwMjksImV4cCI6MjA2ODQyMzAyOX0.bpYT7qnmkrB7uO4VMezeN5vPgrG-w9RvqGpY7LI6xK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});